"use client";

import { CheckCircle2, FileBadge, Upload } from "lucide-react";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export function ExternalCertificateForm({ userId }: { userId: string }) {
  const [title, setTitle] = useState(""); const [issuer, setIssuer] = useState(""); const [hours, setHours] = useState(""); const [issuedAt, setIssuedAt] = useState(""); const [file, setFile] = useState<File | null>(null); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!file) { setError("Anexe o arquivo do certificado."); return; } setSaving(true); setSaved(false); setError(null); const supabase = createClient(); const extension = file.name.split(".").pop() ?? "pdf"; const path = `${userId}/${crypto.randomUUID()}.${extension}`; const { error: uploadError } = await supabase.storage.from("certificates").upload(path, file, { contentType: file.type }); if (uploadError) { setError("Não foi possível enviar o certificado."); setSaving(false); return; } const { error: insertError } = await supabase.from("external_certifications").insert({ user_id: userId, title: title.trim(), issuer: issuer.trim() || null, workload_hours: Number(hours) || 0, issued_at: issuedAt || null, file_url: path }); if (insertError) { setError("Arquivo enviado, mas não foi possível registrar os dados."); setSaving(false); return; } setTitle(""); setIssuer(""); setHours(""); setIssuedAt(""); setFile(null); setSaved(true); setSaving(false); }
  return <form onSubmit={submit} className="space-y-4"><div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-primary"><FileBadge className="size-5" /></div><div><p className="font-medium">Adicionar certificado</p><p className="text-xs text-muted-foreground">Registre uma formação que você já concluiu.</p></div></div><div className="space-y-2"><Label htmlFor="certificate-title">Nome do certificado</Label><Input id="certificate-title" required value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Ex.: Google Data Analytics" className="h-11" /></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="certificate-issuer">Instituição emissora</Label><Input id="certificate-issuer" value={issuer} onChange={(event) => setIssuer(event.target.value)} placeholder="Ex.: Coursera" className="h-11" /></div><div className="space-y-2"><Label htmlFor="certificate-hours">Carga horária</Label><Input id="certificate-hours" required type="number" min="0" value={hours} onChange={(event) => setHours(event.target.value)} placeholder="Ex.: 40" className="h-11" /></div></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="certificate-date">Data de emissão</Label><Input id="certificate-date" type="date" value={issuedAt} onChange={(event) => setIssuedAt(event.target.value)} className="h-11" /></div><div className="space-y-2"><Label htmlFor="certificate-file">Arquivo</Label><Input id="certificate-file" required type="file" accept="application/pdf,image/png,image/jpeg" onChange={(event) => setFile(event.target.files?.[0] ?? null)} className="h-11 pt-2" /></div></div>{error && <p role="alert" className="rounded-lg bg-destructive/10 px-3 py-2 text-sm text-destructive">{error}</p>}{saved && <p role="status" className="flex items-center gap-2 text-sm text-emerald-700 dark:text-emerald-400"><CheckCircle2 className="size-4" /> Certificado adicionado à sua trajetória.</p>}<Button type="submit" disabled={saving || !title.trim() || !hours}><Upload />{saving ? "Enviando..." : "Anexar certificado"}</Button></form>;
}