"use client";

import { CheckCircle2, ListChecks, Plus } from "lucide-react";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

export function SelectionForm({ creatorId, institutionId }: { creatorId: string; institutionId: string | null }) {
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [stages, setStages] = useState("Inscrição, Análise, Entrevista, Resultado"); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setSaved(false); setError(null); const supabase = createClient(); const { data, error: selectionError } = await supabase.from("selections").insert({ title: title.trim(), description: description.trim() || null, published: true, created_by: creatorId, institution_id: institutionId }).select("id").single(); if (selectionError || !data) { setError("Não foi possível publicar a seleção."); setSaving(false); return; } const stageNames = stages.split(",").map((stage) => stage.trim()).filter(Boolean); const { error: stagesError } = await supabase.from("selection_stages").insert(stageNames.map((name, index) => ({ selection_id: data.id, title: name, position: index + 1 }))); if (stagesError) { setError("Seleção criada, mas não foi possível salvar as etapas."); setSaving(false); return; } setTitle(""); setDescription(""); setSaved(true); setSaving(false); window.location.reload(); }
  return <form onSubmit={submit} className="space-y-5"><div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-primary"><ListChecks className="size-5" /></div><div><p className="font-medium">Novo processo seletivo</p><p className="text-xs text-muted-foreground">Defina etapas claras para acompanhar candidatos.</p></div></div><div className="space-y-2"><Label htmlFor="selection-title">Título</Label><Input id="selection-title" required value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Ex.: Programa de estágio 2026" className="h-11" /></div><div className="space-y-2"><Label htmlFor="selection-description">Descrição</Label><Textarea id="selection-description" value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Explique o objetivo e o público do processo." /></div><div className="space-y-2"><Label htmlFor="selection-stages">Etapas</Label><Input id="selection-stages" required value={stages} onChange={(event) => setStages(event.target.value)} className="h-11" /><p className="text-xs text-muted-foreground">Separe cada etapa por vírgula.</p></div>{error && <p role="alert" className="rounded-lg bg-destructive/10 px-3 py-2 text-sm text-destructive">{error}</p>}{saved && <p role="status" className="flex items-center gap-2 text-sm text-emerald-700 dark:text-emerald-400"><CheckCircle2 className="size-4" /> Processo publicado.</p>}<Button type="submit" disabled={saving || !title.trim()}><Plus />{saving ? "Publicando..." : "Publicar seleção"}</Button></form>;
}